Question Display with Pagination
TheCodingForceUPSLP/marathon-quiz-game pull request #51
Opened 2024-11-30 02:31 UTC by Starfisheunyoung

**Description** 
This Pull Request introduces the functionality for displaying questions in pages, where each page contains a set of 5 questions

**Features Implemented:**

1. **Display Questions in Pages**:

   - Questions are displayed in pages, with a maximum of 5 questions per page.

   - The user can navigate between pages using the options 1. for Next page, and 2. for exiting to the menu. 

   - Each question on the page shows the question text, options, and the correct answer.

2. **Pagination System**:

   - The pagination system dynamically calculates the total number of pages based on the number of questions and the number of questions to be shown per page.

   - Proper handling of the navigation between pages ensures that the user can scroll through all the questions without going out of bounds.

3. **Improved User Interaction**:

   - A clear and user-friendly interface is provided with options to navigate through the pages of questions or return to the main menu.

## Tasks Completed:

- Implemented the pagination system to display 5 questions per page.

- Displayed question details (text, options, correct answer) in a user-friendly format.

-Added functionality for navigating between pages.

-Implemented "Exit to Menu" option for easy return to the main menu.

2024-11-30 17:46 UTC, Friedamariao commented on marathon_quiz.cpp
> +void displayQuestionsInPages(Question* questionHead)
@Starfisheunyoung Please add the missing semicolon at the end of the function prototype displayQuestionsInPages

2024-11-30 17:50 UTC, Friedamariao commented on marathon_quiz.cpp
> +            	displayQuestionsInPages(Question* questionHead);
@Starfisheunyoung 
- In line 149, let's leave out the type declaration inside of the function call, it's only needes the quesionHead. 
- Please also add, the break sentence at the end of case 8.

2024-11-30 17:53 UTC, Friedamariao requested changes

2024-11-30 17:53 UTC, Friedamariao commented on marathon_quiz.cpp
> +void displayQuestionsInPages(Question* questionHead)
@Starfisheunyoung Please add the missing semicolon at the end of the function displayQuestionsInPages

2024-11-30 17:53 UTC, Friedamariao commented on marathon_quiz.cpp
> +            	displayQuestionsInPages(Question* questionHead);
@Starfisheunyoung 
- In line 149, let's leave out the type declaration inside of the function call, it's only needes the quesionHead. 
- Please also add, the break sentence at the end of case 8.

2024-11-30 18:08 UTC, Friedamariao requested changes

2024-11-30 18:08 UTC, Friedamariao commented on marathon_quiz.cpp
> +void displayQuestionsInPages(Question* questionHead) {
@Starfisheunyoung
I think there might be some issues with the logic of the function. After making the necessary changes to get the program to compile correctly, here are the problems I noticed:

- The functionality allows moving to the next page, but it doesn't work when trying to go back to the previous page; it just says "try again."
- The first question on the second page is numbered as '1' again, but it should continue from the previous page, showing 6, 7, 8, and so on.
- Lastly, the page numbers seem to be off. On the first page, it correctly displays "Page 1 of 2," but on the second page, it shows "Page 1 of 1."

You might want to check the `printPlayers` function, which also has a pagination system that works like this one should work!

2024-12-05 18:51 UTC, gfdfranco approved these changes
LGTM

2024-12-05 22:34 UTC, DanielRV3 approved these changes
LGTM

2024-12-05 22:35 UTC, Friedamariao approved these changes

2024-12-05 23:05 UTC, merged