Category implementation in ModifyQuestionById
TheCodingForceUPSLP/marathon-quiz-game pull request #53
Opened 2024-12-02 06:53 UTC by leonardomedinaa

**Description**
This PR updates the modifyQuestionById function to allow modifications to the category field in questions. The changes include:

- Support for category editing: Added functionality to update the category of an existing question.
- Category validation: Ensures that the entered category is within the allowed range (1-6).
- Improved interface: Displays the current category of the question and prompts the user to update it during the modification process.

**Testing**

- Verified successful updates for questions with various categories.
- Ensured proper validation for categories within the valid range.
- Handled edge cases where invalid categories (outside the range) were entered.

Closes #14

2024-12-03 05:11 UTC, gfdfranco requested changes
Just a little fix, ty !

2024-12-03 05:11 UTC, gfdfranco commented on marathon_quiz.cpp
> +				modifyQuestionById(questionHead, questionId, category);
Please fix the indentation of this code block

2024-12-03 05:15 UTC, gfdfranco approved these changes
LGTM

2024-12-03 05:28 UTC, Friedamariao approved these changes
LGTM

2024-12-04 01:43 UTC, OliverHerrera140 approved these changes
LGTM

2024-12-04 15:19 UTC, merged